In [1]:
#conda install numpy

In [2]:
import numpy as np

In [3]:
#Numpy Arrays
my_list = [1,2,3]

In [4]:
nparr = np.array(my_list)

In [5]:
nparr

array([1, 2, 3])

In [6]:
#two dimentional 
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
#zeros and ones
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#linspace
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
#eye
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#Random
# uniform distribution
np.random.rand(2)

array([0.60997038, 0.99876834])

In [19]:
#standard normal distribution
np.random.randn(2)

array([-0.78150272, -0.60916889])

In [20]:
#standard normal distribution
np.random.randn(5,5)

array([[ 1.3048148 , -0.9129286 , -0.92529189,  2.18518524,  0.85770073],
       [-0.5162255 ,  0.22264888,  0.63074807, -0.87212353, -0.71161469],
       [-0.51545099, -0.18515681, -1.22034111,  0.26655142,  1.05849794],
       [ 0.0086272 ,  0.48136463, -0.65078213,  0.56343712,  0.23858059],
       [-1.89454053, -0.59125135,  2.18951826, -1.586915  , -0.78736579]])

In [21]:
np.random.randint(1,100)

20

In [22]:
np.random.randint(1,100,13)

array([94, 52,  4, 40, 52, 90, 98, 84, 78, 65, 44, 78, 32])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
#Reshape: changes dimension of an array
arr.reshape(4,6)

ValueError: cannot reshape array of size 25 into shape (4,6)

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr.max()

49

In [29]:
ranarr

array([49, 17,  7, 46, 35, 41, 20, 12,  9, 40])

In [30]:
ranarr.argmax()

0

In [31]:
ranarr[0]

49

In [32]:
ranarr.min()

7

In [33]:
ranarr.argmin()

2

In [34]:
ranarr.shape

(10,)

In [37]:
arr2 = arr.reshape(5,5)

In [38]:
arr2.shape

(5, 5)

In [39]:
arr2.dtype

dtype('int32')

In [40]:
#indexing and selection
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
#value at specific position
arr[8]

8

In [42]:
#get values in range
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[9:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
#Broadcasting
arr[0:5] = 500
arr

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [47]:
slice_of_Array = arr[4:9]
slice_of_Array

array([500,   5,   6,   7,   8])

In [48]:
slice_of_Array[:] = 900

In [49]:
slice_of_Array

array([900, 900, 900, 900, 900])

In [50]:
arr

array([500, 500, 500, 500, 900, 900, 900, 900, 900,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [51]:
#copy
arr_copy = arr.copy()

In [52]:
arr_copy

array([500, 500, 500, 500, 900, 900, 900, 900, 900,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [53]:
arr_copy[:] = 765

In [54]:
arr_copy

array([765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765,
       765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765, 765])

In [55]:
arr

array([500, 500, 500, 500, 900, 900, 900, 900, 900,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [56]:
arr2d = np.array([[5,10,15],[20,25,30],[40,45,50]])

In [57]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [40, 45, 50]])

In [58]:
arr2d[1]

array([20, 25, 30])

In [59]:
arr2d[1][1]

25

In [60]:
#same result different syntax
arr2d[1,1]

25

In [61]:
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [62]:
arr2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [63]:
arr2d[0:2,1:2]

array([[10],
       [25]])

In [64]:
#selection
arr = np.arange(1,11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
#operations
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [72]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
newarr = np.arange(0,10)

In [75]:
newarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
newarr / newarr

<ipython-input-76-056b266ea0b0>:1: RuntimeWarning: invalid value encountered in true_divide
  newarr / newarr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [77]:
1/0

ZeroDivisionError: division by zero

In [78]:
#universal functions
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [79]:
np.max(arr)

10

In [80]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [82]:
#get common items between two arrays (numpy)
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([2,4,6,8,10,12,14,16])

np.intersect1d(a,b)

array([2, 4, 6, 8])

In [83]:
#remove from array those that exist in another
np.setdiff1d(a,b)

array([1, 3, 5, 7, 9])

In [84]:
#swap two columns in 2d array
swap2d = np.arange(9).reshape(3,3)
swap2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
swap2d[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [86]:
#reverse
swap2d[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [88]:
swap2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
swap2d[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [90]:
#find max in 2d array 
swap2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
#axis=1 is rows
np.amax(swap2d,axis=1)

array([2, 5, 8])

In [92]:
np.amax(swap2d)

8

In [93]:
#axis=0 is columns
np.amax(swap2d,axis=0)

array([6, 7, 8])

In [94]:
#drop missing values
bad_Data = np.array([1,2,3,np.nan,5,np.nan,7,np.nan])
bad_Data

array([ 1.,  2.,  3., nan,  5., nan,  7., nan])

In [95]:
bad_Data[np.isnan(bad_Data)]

array([nan, nan, nan])

In [96]:
bad_Data[~np.isnan(bad_Data)]

array([1., 2., 3., 5., 7.])

In [97]:
bad_Data[!np.isnan(bad_Data)]

SyntaxError: invalid syntax (<ipython-input-97-10c3225f3630>, line 1)