#### Import Numpy, Pandas, Matplot and Seaborn to complete these Exercises

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#### Using Numpy create a 1D array with 5 elements: (ex. array([0, 1, 2, 3, 4]))

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

#### Extract all the numbers from the array below that are greater than 5

In [10]:
arr = np.arange(30)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29])

#### Convert the following 1D array to a 2D array with 3 rows:

In [17]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### Change the values of the following array to 32

In [20]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr[:] = 32

In [22]:
arr

array([32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32])

#### Change the index of the data frame to numeric index

In [43]:
df = pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A  0.649821  0.438511  0.847735 -0.366717
B  1.821030 -1.747434 -0.138682 -1.220638
C  1.035876  0.977709  0.079623 -1.556038
D  0.084888  0.849006 -1.285550  1.895493
E -1.192359  1.114261 -2.562708  1.387175

In [50]:
df.reset_index().head()
df

index         W         X         Y         Z
0     A  0.649821  0.438511  0.847735 -0.366717
1     B  1.821030 -1.747434 -0.138682 -1.220638
2     C  1.035876  0.977709  0.079623 -1.556038
3     D  0.084888  0.849006 -1.285550  1.895493
4     E -1.192359  1.114261 -2.562708  1.387175

#### Add a new column to the dataframe "df" that concatenates both columns X & W

In [52]:
df['newColumn'] = df['X'] + df['W']

In [54]:
df

index         W         X         Y         Z  newColumn
0     A  0.649821  0.438511  0.847735 -0.366717   1.088332
1     B  1.821030 -1.747434 -0.138682 -1.220638   0.073595
2     C  1.035876  0.977709  0.079623 -1.556038   2.013585
3     D  0.084888  0.849006 -1.285550  1.895493   0.933893
4     E -1.192359  1.114261 -2.562708  1.387175  -0.078098

In [5]:
arr = np.arange(24).reshape(3,8)
df = pd.DataFrame(arr,index='A B C'.split(),columns='R S T V W X Y Z'.split())
df

R   S   T   V   W   X   Y   Z
A   0   1   2   3   4   5   6   7
B   8   9  10  11  12  13  14  15
C  16  17  18  19  20  21  22  23

#### Extract Row A
#### Extract all rows with value greater than 9
#### Extract Row C and Columns X,Y and Z

In [7]:
df.loc['A']

R    0
S    1
T    2
V    3
W    4
X    5
Y    6
Z    7
Name: A, dtype: int32

In [9]:
df[df>10]

R     S     T     V     W     X     Y     Z
A   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
B   NaN   NaN   NaN  11.0  12.0  13.0  14.0  15.0
C  16.0  17.0  18.0  19.0  20.0  21.0  22.0  23.0

In [10]:
df.loc[['C'],['X','Y','Z']]

X   Y   Z
C  21  22  23